# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")];

  # boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  # boot.initrd.kernelModules = [ ];
  # boot.kernelModules = [ "kvm-intel" ];
  # boot.extraModulePackages = [ ];

    boot = {      
        extraModulePackages = [ ];                                # boot options
        kernelPackages = pkgs.linuxPackages_cachyos;               # kernel version and type to boot
        kernelModules = [ "nvidia" "kvm-intel" ];                             # kernel modules, like drivers
        loader = {                              # options for bootloaders
            efi = {                             # basic efi options needed for UEFI systems
                canTouchEfiVariables = true;
                efiSysMountPoint = "/boot";
            };
            grub = {
				configurationLimit = 5;
                default = "0";
                # device = ;
                # devices = [ ... ];
                efiInstallAsRemovable = false;
                efiSupport = false;
                enable = false;
                font = "${pkgs.grub2}/share/grub/unicode.pf2";
                fontSize = 16;
                # theme = ;
                # users = { ... };
            };
            systemd-boot = {                    # systemd-boot options, see https://nixos.wiki/wiki/Bootloader for more
		        configurationLimit = 5;         # limits of generation
                enable = true;                  # toggle for enabling systemd-boot
                memtest86 = {                   # options for memtest86 or https://www.memtest86.com/
                    enable = true;              
                    sortKey = "o_memtest86";    
                };
                netbootxyz = {                  # options for netbootxyz or https://netboot.xyz/
                    enable = false;
                    sortKey = "o_netbootxyz";
                };
                sortKey = "nixos";              # https://uapi-group.org/specifications/specs/boot_loader_specification/#sorting
            };
        };
		initrd = {
			availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
            kernelModules = [ "kvm-intel" ];
            checkJournalingFS = false;
        };
        supportedFilesystems = [ ];     # supported FSes modules
    };

	fileSystems = {
        "/" = { 
            device = "/dev/disk/by-label/root";
            fsType = "f2fs";
        };
		"/mnt/hdd" = {
            device = "/dev/disk/by-label/hdd";
            fsType = "ext4";  
        };
        "/boot" = {
            device = "/dev/disk/by-label/boot";
            fsType = "vfat";
            options = [ "fmask=0022" "dmask=0022" ];
        };

		swapDevices =
			[ { device = "/dev/disk/by-label/swap"; }];
    };


    hardware = {
		cpu = {
            intel = {
                updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; # NEED to be like this
                sgx = {
                    enableDcapCompat = true;
                    provision = {
                        enable = false;
                        group = "sgx_prv";
                        mode = "0660";
                        user = "root";
                    };
                };
            };
		};
        nvidia = {                              # read this - https://wiki.nixos.org/wiki/Nvidia
            datacenter = {
                enable = false;
                settings = {};
            };
            modesetting.enable = false;
            nvidiaSettings = true;
            open = false;
            package = "config.boot.kernelPackages.nvidiaPackages.beta";
            powerManagement = {
                enable = false;
                finegrained = false;
            };
            prime = {
                allowExternalGpu = false;
                amdgpuBusId = "";
                intelBusId = "";
                nvidiaBusId = "";
                offload = {
                    enable = false;
                    enableOffloadCmd = false;
                };
                reverseSync = {
                    enable = false;
                    setupCommands.enable = false;
                };
                sync.enable = false;
            };
        };
        bluetooth = { 
            enable = true; 
            powerOnBoot = true;
        };
		graphics = {                  # cruical part for proper GPU working
	        enable = true;
            enable32Bit = true;
		};
	    opengl = {
            enable = true;
            driSupport = true;
            driSupport32Bit = true;   
        };
    };
}
